// <auto-generated />
using System;
using CRUDExam.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CRUDExam.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200903082616_AddRelationFixed")]
    partial class AddRelationFixed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CRUDExam.Data.Models.Permission", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date_Permission")
                        .HasColumnType("datetime2");

                    b.Property<string>("Emp_LastName")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Emp_Name")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("Permission_Type")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("Permission_Type");

                    b.ToTable("Permission");
                });

            modelBuilder.Entity("CRUDExam.Data.Models.PermissionType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("ID");

                    b.ToTable("PermissionType");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "Enfermedad"
                        },
                        new
                        {
                            ID = 2,
                            Description = "Diligencias"
                        },
                        new
                        {
                            ID = 3,
                            Description = "Descanso"
                        });
                });

            modelBuilder.Entity("CRUDExam.Data.Models.Permission", b =>
                {
                    b.HasOne("CRUDExam.Data.Models.PermissionType", "PermissionType")
                        .WithMany("Permission")
                        .HasForeignKey("Permission_Type")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
